services:
  impact-flow:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
        CORS_ALLOW_ORIGIN: 'http://localhost:5173;http://localhost:8080'
        ENABLE_WEB_SEARCH: 'false'
        WEBUI_SECRET_KEY: 'Pqbp2afD2QJFfI+V'
      dockerfile: Dockerfile
    image: impact-flow:latest
    container_name: impact-flow
    volumes:
      - impact-flow:/app/backend/data
    ports:
      - '3000:8080'
    environment:
      - 'CORS_ALLOW_ORIGIN=http://localhost:5173;http://localhost:8080'
      - 'ENABLE_WEB_SEARCH=false'
      - 'OLLAMA_BASE_URL=http://localhost:11434'
      - 'WEBUI_SECRET_KEY=Pqbp2afD2QJFfI+V'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  impact-flow: {}
