product_names = [
    "Algenkraft",
    "Algenkraft",
    "Alka Box",
    "Astragalus 10",
    "Augenkraft",
    "Ayurveda Balance",
    "Beauty Complex",
    "Blutdruck-Komplex",
    "Blutzucker-Komplex",
    "Bupleurum 9",
    "Burner",
    "COLLAGEN Shots Refill (100 Stück)",
    "Chili choco shake",
    "Cholesterin-Komplex",
    "Cythula 12",
    "Daily 365",
    "Darmkraft",
    "Eiweiss-Vitalkomplex",
    "Enzymkraft",
    "Ethno Health Coach",
    "Ethno-Hausapotheke",
    "Ethno-Testsatz",
    "Forsythiae 10",
    "Frauenkraft",
    "Gehirnkraft",
    "Gelenkkraft",
    "HS-Omega-3 Index-Selbsttest",
    "Herzkraft",
    "Immunkraft",
    "Inflam-Komplex",
    "Lebensfreude",
    "Leberkraft",
    "Lung - inkl. Präsentbox",
    "Lungenkraft",
    "MSM greens",
    "Männerkraft",
    "OPC-Kraft",
    "Omega 3 orange",
    "Omega 3 plus",
    "Omega Duo",
    "Omega Go!",
    "Pilzkraft",
    "Polygoni 7",
    "Rehmannia 6",
    "Schisandra 13",
    "Shape Classic",
    "Vorzugspaket TCR",
    "Weidenkraft",
    "Wurzel-Komplex",
    "Zellschutz-Komplex",
    "Ziziphus 9",
    "alka duo",
    "daily B-complex",
    "daily zenergy",
    "essence aminos",
    "fresh vanilla shake",
    "wild berry shake",
]

categories_enum = [
    "Beauty & Lifestyle",
    "Body & Clean",
    "Bundles",
    "Chinesische Rezepturen",
    "Ethno Health Coach",
    "Ethno-Events",
    "Ethno-Hausapotheke",
    "Ethno-Rezepturen",
    "Ethno-Rezepturen, Für Kinder geeignet",
    "Ethno-Testsatz",
    "Für Kinder geeignet",
    "Omega Go!",
    "Omega-Öle & Vitalkomplex ",
    "Omega-Öle & Vitalkomplex, Für Kinder geeignet",
    "Produktübersicht",
    "Shape Classic, Shape Weight Management",
    "Shape Weight Management",
    "Tibetische Rezeptur Lung",
    "Vitality & Family",
    "Vorzugspaket TCR",
]
